### ISSUE TITLE
Enhancement to provide defaults/templates for new 

### ISSUE THREAD

**Issue by dupuy** [dupuy/reliabot#104]
## Describe the solution you want to see

_Explain how you want Reliabot to work, providing as many details as possible._

When reliabot creates a new directory entry in `dependabot.yml`, it uses minimal
built-in configuration:
```yaml
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
```

However, you might prefer a longer interval, and for certain frequently updated
packages (such as AWS SDKs like `boto*`) you might want to add an `ignore`
section to skip patch updates for version and not security:
```yaml
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
        # For AWS SDK, ignore patch version (not security) updates
      - dependency-name: "aws-sdk"
        update-types: ["version-update:semver-patch"]
```

## Outline alternatives you've considered

A command-line option `--default-interval` and a simple reliabot-comment
`default-interval` setting for the `dependabot.yml` file itself would handle the
most basic case. This would be quite a good first issue to implement.

For settings specific to package ecosystem (whether `interval` or `ignore` or
something else, it may be possible to use non-comment configuration for a dummy
`.reliabot-defaults` directory (which might not even need to exist, if
Dependabot doesn't complain about that).

An advantage of using "live" configuration is that Dependabot parses and
validates it, so that typos or syntax errors can be caught immediately. Default
configuration in comments would pass no matter how egregious the errors, and
Dependabot semantic errors in other YAML configuration files would not be
checked until and unless copied to `dependabot.yml`.  (Using other files would
also split the configuration into multiple locations.)

## Provide a rationale

_Explain why this enhancement would be useful to many reliabot users._

Being able to configure defaults for newly added code locations can eliminate
any need to edit them when they are created, further automating the process.
